//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConservatorioVANew.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_a6dce2_mozartvaEntities : DbContext
    {
        public db_a6dce2_mozartvaEntities()
            : base("name=db_a6dce2_mozartvaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Alumno> Alumno { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Instrumento> Instrumento { get; set; }
        public virtual DbSet<Profesor> Profesor { get; set; }
        public virtual DbSet<Registro> Registro { get; set; }
        public virtual DbSet<TipoCategoria> TipoCategoria { get; set; }
    }
}
