//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConservatorioVANew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registro
    {
        public int idRegistro { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public decimal montoRegistro { get; set; }
        public int idCategoria { get; set; }
        public int idResponsable { get; set; }
        public string descripcionRegistro { get; set; }
        public Nullable<int> idProfesor { get; set; }
        public Nullable<int> idAlumno { get; set; }
        public string formaDePago { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Profesor Profesor { get; set; }
    }
}
